apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cds.yamecloud.io
spec:
  group: yamecloud.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                ServiceName:
                  type: string
                DeployNamespace:
                  type: string
                ArtifactInfo:
                  type: object
                retryCount:
                  type: integer
                DeployType:
                  type: string
                flowId:
                  type: string
                stepName:
                  type: string
                ackStates:
                  type: array
                  items:
                    type: string
                uuid:
                  type: string
                done:
                  type: boolean

      additionalPrinterColumns:
        - name: ServiceName
          type: string
          jsonPath: .spec.serviceName
        - name: DeployNamespace
          type: string
          jsonPath: .spec.deployNamespace
        - name: RetryCount
          type: string
          jsonPath: .spec.retryCount
        - name: DeployType
          type: string
          jsonPath: .spec.deployType
        - name: FlowId
          type: string
          jsonPath: .spec.flowId
        - name: StepName
          type: string
          jsonPath: .spec.stepName
        - name: AckStates
          type: string
          jsonPath: .spec.ackStates
        - name: UUID
          type: string
          jsonPath: .spec.uuid
        - name: Done
          type: boolean
          jsonPath: .spec.done
  scope: Namespaced
  names:
    plural: cds
    singular: cd
    kind: CD
    shortNames:
      - cd