apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ci.yamecloud.io
spec:
  group: yamecloud.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gitUrl:
                  type: string
                commitId:
                  type: string
                retryCount:
                  type: integer
                output:
                  type: string
      additionalPrinterColumns:
        - name: VlanID
          type: string
          jsonPath: .spec.vlanId
        - name: ProviderInterfaceName
          type: string
          jsonPath: .spec.providerInterfaceName
        - name: Subnet
          type: string
          jsonPath: .spec.subnet
  scope: Cluster
  names:
    plural: vlans
    singular: vlan
    kind: Vlan
    shortNames:
      - vlan