apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cds.yamecloud.io
spec:
  group: yamecloud.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gitUrl:
                  type: string
                commitId:
                  type: string
                retryCount:
                  type: integer
                output:
                  type: string
      additionalPrinterColumns:
        - name: GitUrl
          type: string
          jsonPath: .spec.gitUrl
        - name: CommitId
          type: string
          jsonPath: .spec.commitId
        - name: RetryCount
          type: string
          jsonPath: .spec.retryCount
        - name: Output
          type: string
          jsonPath: .spec.output
  scope: Namespaced
  names:
    plural: cds
    singular: cd
    kind: CD
    shortNames:
      - cd