apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cis.yamecloud.io
spec:
  group: yamecloud.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gitUrl:
                  type: string
                branch:
                  type: string
                commitId:
                  type: string
                codeType:
                  type: string
                retryCount:
                  type: integer
                output:
                  type: string
                flowId:
                  type: string
                stepName:
                  type: string
                ackStates:
                  type: array
                  items:
                    type: string
                uuid:
                  type: string
                done:
                  type: boolean
                projectPath:
                  type: string
                projectFile:
                  type: string
      additionalPrinterColumns:
        - name: GitUrl
          type: string
          jsonPath: .spec.gitUrl
        - name: Branch
          type: string
          jsonPath: .spec.branch
        - name: CommitId
          type: string
          jsonPath: .spec.commitId
        - name: CodeType
          type: string
          jsonPath: .spec.codeType
        - name: RetryCount
          type: string
          jsonPath: .spec.retryCount
        - name: Output
          type: string
          jsonPath: .spec.output
        - name: FlowId
          type: string
          jsonPath: .spec.flowId
        - name: StepName
          type: string
          jsonPath: .spec.stepName
        - name: AckStates
          type: string
          jsonPath: .spec.ackStates
        - name: UUID
          type: string
          jsonPath: .spec.uuid
        - name: Done
          type: boolean
          jsonPath: .spec.done
        - name: ProjectPath
          type: string
          jsonPath: .spec.projectPath
        - name: ProjectFile
          type: string
          jsonPath: .spec.projectFile
  scope: Namespaced
  names:
    plural: cis
    singular: ci
    kind: CI
    shortNames:
      - ci